let
    actualUrl = "https://redcap.AcademicExtension.edu/api/",
    record = [
    token="TOKEN",
    content="record",
    format="csv",
    rawOrLabel="label"
    ],
    body = Text.ToBinary(Uri.BuildQueryString(record)),
    options = [Headers =[#"Content-type"="application/x-www-form-urlencoded"], Content=body],
    result = Web.Contents(actualUrl, options),
    #"Imported CSV" = Csv.Document(result,[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true])

in #"Promoted Headers"